CREATE TABLE users (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             UUID NOT NULL UNIQUE,
    first_name          VARCHAR(255),
    last_name           VARCHAR(255),
    email               VARCHAR(255) NOT NULL UNIQUE,
    password            VARCHAR(255),
    date_inscription    TIMESTAMP,
    role                VARCHAR(50)
);

CREATE TABLE commercants (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    commercant_id       UUID NOT NULL UNIQUE,
    user_id             BIGINT NOT NULL UNIQUE REFERENCES users (id),
    nom_boutique        VARCHAR(255),
    adresse             VARCHAR(255),
    latitude            DOUBLE PRECISION,
    longitude           DOUBLE PRECISION,
    categorie           VARCHAR(50),
    photo               VARCHAR(255),
    horaires_ouverture  VARCHAR(255)
);

CREATE TABLE paniers (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    panier_id               UUID NOT NULL UNIQUE,
    commercant_id           BIGINT NOT NULL REFERENCES commercants (id),
    description             VARCHAR(1000),
    prix_reduit             NUMERIC(10, 2),
    valeur_estimee          NUMERIC(10, 2),
    quantite_initiale       INTEGER NOT NULL,
    quantite_restante       INTEGER NOT NULL,
    heure_debut_retrait     TIME,
    heure_fin_retrait       TIME,
    date_disponibilite      DATE,
    status                  VARCHAR(50)
);

CREATE TABLE reservations (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id      UUID NOT NULL UNIQUE,
    user_id             BIGINT NOT NULL REFERENCES users (id),
    panier_id           BIGINT NOT NULL REFERENCES paniers (id),
    quantite_reservee   INTEGER NOT NULL,
    status_reservation  VARCHAR(50),
    date_reservation    TIMESTAMP,
    qr_code             VARCHAR(255)
);
